name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5.4.0
        with:
          python-version: '3.12'
      - run: uvx poetry install
      - run: uvx poetry run pytest -v -ra --cov --cov-report=term-missing
        env:
          COVERAGE_CORE: sysmon
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5.4.0
        with:
          python-version: '3.12'
      - run: uv build .
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check
      - run: ruff format --check
