name: Unit tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install poetry
          poetry install
      - name: Run python tests
        run: |
          poetry run pytest
